// Copyright (C) 2026 LeRedTeam
// SPDX-License-Identifier: AGPL-3.0-or-later

package policy

import (
	"encoding/json"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func testDoc() *Document {
	return &Document{
		Version: "2012-10-17",
		Statement: []Statement{
			{
				Effect:   "Allow",
				Action:   []string{"s3:GetObject", "s3:PutObject"},
				Resource: "arn:aws:s3:::my-bucket/*",
			},
		},
	}
}

func TestToYAMLValid(t *testing.T) {
	doc := testDoc()
	out, err := doc.ToYAML()
	if err != nil {
		t.Fatalf("ToYAML error: %v", err)
	}

	// Should be valid YAML
	var parsed map[string]interface{}
	if err := yaml.Unmarshal(out, &parsed); err != nil {
		t.Fatalf("Output is not valid YAML: %v", err)
	}

	// With yaml struct tags, keys should be PascalCase
	if parsed["Version"] != "2012-10-17" {
		t.Errorf("Version = %v, want 2012-10-17", parsed["Version"])
	}
}

func TestToYAMLEmpty(t *testing.T) {
	doc := &Document{Version: "2012-10-17", Statement: []Statement{}}
	out, err := doc.ToYAML()
	if err != nil {
		t.Fatalf("ToYAML error: %v", err)
	}
	if len(out) == 0 {
		t.Error("Expected non-empty YAML output")
	}
}

func TestToTerraformValid(t *testing.T) {
	doc := testDoc()
	out, err := doc.ToTerraform("my_policy")
	if err != nil {
		t.Fatalf("ToTerraform error: %v", err)
	}

	output := string(out)

	checks := []string{
		`resource "aws_iam_policy" "my_policy"`,
		`name        = "my_policy"`,
		`description = "Generated by iampg"`,
		`policy = <<-EOF`,
		`EOF`,
		`s3:GetObject`,
		`2012-10-17`,
	}
	for _, check := range checks {
		if !strings.Contains(output, check) {
			t.Errorf("Terraform output missing %q", check)
		}
	}
}

func TestToTerraformDefaultResourceName(t *testing.T) {
	doc := testDoc()
	out, err := doc.ToTerraform("")
	if err != nil {
		t.Fatalf("ToTerraform error: %v", err)
	}

	if !strings.Contains(string(out), "generated_policy") {
		t.Error("Expected default resource name 'generated_policy'")
	}
}

func TestToTerraformContainsValidJSON(t *testing.T) {
	doc := testDoc()
	out, err := doc.ToTerraform("test")
	if err != nil {
		t.Fatalf("ToTerraform error: %v", err)
	}

	// Extract JSON between EOF markers
	output := string(out)
	start := strings.Index(output, "<<-EOF\n") + len("<<-EOF\n")
	end := strings.Index(output, "\n  EOF")
	if start < 0 || end < 0 || end <= start {
		t.Fatal("Could not find JSON between EOF markers")
	}

	jsonStr := strings.TrimSpace(output[start:end])
	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(jsonStr), &parsed); err != nil {
		t.Errorf("JSON inside Terraform heredoc is invalid: %v\nJSON: %s", err, jsonStr)
	}
}

func TestToSARIFValid(t *testing.T) {
	doc := testDoc()
	out, err := doc.ToSARIF("1.0.0")
	if err != nil {
		t.Fatalf("ToSARIF error: %v", err)
	}

	var report SARIFReport
	if err := json.Unmarshal(out, &report); err != nil {
		t.Fatalf("Output is not valid SARIF JSON: %v", err)
	}

	if report.Version != "2.1.0" {
		t.Errorf("SARIF version = %q, want 2.1.0", report.Version)
	}
	if len(report.Runs) != 1 {
		t.Fatalf("Runs = %d, want 1", len(report.Runs))
	}
	if report.Runs[0].Tool.Driver.Name != "iampg" {
		t.Errorf("Tool name = %q, want iampg", report.Runs[0].Tool.Driver.Name)
	}
	if report.Runs[0].Tool.Driver.Version != "1.0.0" {
		t.Errorf("Tool version = %q, want 1.0.0", report.Runs[0].Tool.Driver.Version)
	}
}

func TestToSARIFDefaultVersion(t *testing.T) {
	doc := testDoc()
	out, err := doc.ToSARIF("")
	if err != nil {
		t.Fatalf("ToSARIF error: %v", err)
	}

	var report SARIFReport
	json.Unmarshal(out, &report)
	if report.Runs[0].Tool.Driver.Version != "0.1.0" {
		t.Errorf("Default version = %q, want 0.1.0", report.Runs[0].Tool.Driver.Version)
	}
}

func TestToSARIFResults(t *testing.T) {
	doc := testDoc()
	out, _ := doc.ToSARIF("1.0.0")

	var report SARIFReport
	json.Unmarshal(out, &report)

	results := report.Runs[0].Results
	// testDoc has 2 non-wildcard actions = 2 permission-detected results
	if len(results) != 2 {
		t.Fatalf("Results = %d, want 2", len(results))
	}
	for _, r := range results {
		if r.RuleID != "iampg/permission-detected" {
			t.Errorf("RuleID = %q, want iampg/permission-detected", r.RuleID)
		}
		if r.Level != "note" {
			t.Errorf("Level = %q, want note", r.Level)
		}
	}
}

func TestToSARIFWildcardDetection(t *testing.T) {
	doc := &Document{
		Version: "2012-10-17",
		Statement: []Statement{
			{Effect: "Allow", Action: []string{"s3:*"}, Resource: "*"},
		},
	}

	out, _ := doc.ToSARIF("1.0.0")
	var report SARIFReport
	json.Unmarshal(out, &report)

	results := report.Runs[0].Results
	// Should have: 1 wildcard-action + 1 wildcard-resource
	hasWildcardAction := false
	hasWildcardResource := false
	for _, r := range results {
		if r.RuleID == "iampg/wildcard-action" {
			hasWildcardAction = true
		}
		if r.RuleID == "iampg/wildcard-resource" {
			hasWildcardResource = true
		}
	}
	if !hasWildcardAction {
		t.Error("Missing wildcard-action result")
	}
	if !hasWildcardResource {
		t.Error("Missing wildcard-resource result")
	}
}

func TestToSARIFRules(t *testing.T) {
	doc := testDoc()
	out, _ := doc.ToSARIF("1.0.0")

	var report SARIFReport
	json.Unmarshal(out, &report)

	rules := report.Runs[0].Tool.Driver.Rules
	if len(rules) != 3 {
		t.Fatalf("Rules = %d, want 3", len(rules))
	}

	ruleIDs := map[string]bool{}
	for _, r := range rules {
		ruleIDs[r.ID] = true
	}
	expected := []string{"iampg/permission-detected", "iampg/wildcard-resource", "iampg/wildcard-action"}
	for _, id := range expected {
		if !ruleIDs[id] {
			t.Errorf("Missing rule %q", id)
		}
	}
}

func TestFormatDispatcher(t *testing.T) {
	doc := testDoc()

	formats := []Format{FormatJSON, FormatYAML, FormatTerraform, FormatSARIF}
	for _, f := range formats {
		t.Run(string(f), func(t *testing.T) {
			opts := map[string]string{"resource_name": "test", "version": "1.0.0"}
			out, err := doc.Format(f, opts)
			if err != nil {
				t.Fatalf("Format(%s) error: %v", f, err)
			}
			if len(out) == 0 {
				t.Errorf("Format(%s) returned empty output", f)
			}
		})
	}
}

func TestFormatUnknown(t *testing.T) {
	doc := testDoc()
	_, err := doc.Format("xml", nil)
	if err == nil {
		t.Error("Expected error for unknown format")
	}
}

func TestToSARIFEmpty(t *testing.T) {
	doc := &Document{Version: "2012-10-17", Statement: []Statement{}}
	out, err := doc.ToSARIF("1.0.0")
	if err != nil {
		t.Fatalf("ToSARIF error: %v", err)
	}

	var report SARIFReport
	json.Unmarshal(out, &report)
	if len(report.Runs[0].Results) != 0 {
		t.Errorf("Expected 0 results for empty policy, got %d", len(report.Runs[0].Results))
	}
}
