package policy

import (
	"encoding/json"
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

// Format represents an output format.
type Format string

const (
	FormatJSON      Format = "json"
	FormatYAML      Format = "yaml"
	FormatTerraform Format = "terraform"
	FormatSARIF     Format = "sarif"
)

// ToYAML converts the policy document to YAML.
func (d *Document) ToYAML() ([]byte, error) {
	return yaml.Marshal(d)
}

// ToTerraform converts the policy document to Terraform HCL.
func (d *Document) ToTerraform(resourceName string) ([]byte, error) {
	if resourceName == "" {
		resourceName = "generated_policy"
	}

	policyJSON, err := d.ToJSON()
	if err != nil {
		return nil, err
	}

	// Indent the JSON for readability inside heredoc
	var prettyJSON map[string]interface{}
	json.Unmarshal(policyJSON, &prettyJSON)
	indentedJSON, _ := json.MarshalIndent(prettyJSON, "  ", "  ")

	hcl := fmt.Sprintf(`resource "aws_iam_policy" "%s" {
  name        = "%s"
  description = "Generated by iampg"

  policy = <<-EOF
  %s
  EOF
}
`, resourceName, resourceName, string(indentedJSON))

	return []byte(hcl), nil
}

// SARIFReport represents a SARIF 2.1.0 report.
type SARIFReport struct {
	Schema  string      `json:"$schema"`
	Version string      `json:"version"`
	Runs    []SARIFRun  `json:"runs"`
}

// SARIFRun represents a single run in a SARIF report.
type SARIFRun struct {
	Tool    SARIFTool    `json:"tool"`
	Results []SARIFResult `json:"results"`
}

// SARIFTool represents the tool that produced the report.
type SARIFTool struct {
	Driver SARIFDriver `json:"driver"`
}

// SARIFDriver represents the tool driver.
type SARIFDriver struct {
	Name    string      `json:"name"`
	Version string      `json:"version"`
	Rules   []SARIFRule `json:"rules"`
}

// SARIFRule represents a rule definition.
type SARIFRule struct {
	ID               string           `json:"id"`
	Name             string           `json:"name"`
	ShortDescription SARIFMessage     `json:"shortDescription"`
	FullDescription  SARIFMessage     `json:"fullDescription"`
	DefaultConfig    SARIFRuleConfig  `json:"defaultConfiguration"`
}

// SARIFRuleConfig represents rule configuration.
type SARIFRuleConfig struct {
	Level string `json:"level"`
}

// SARIFResult represents a single result.
type SARIFResult struct {
	RuleID    string         `json:"ruleId"`
	Level     string         `json:"level"`
	Message   SARIFMessage   `json:"message"`
	Locations []SARIFLocation `json:"locations,omitempty"`
}

// SARIFMessage represents a message.
type SARIFMessage struct {
	Text string `json:"text"`
}

// SARIFLocation represents a location.
type SARIFLocation struct {
	PhysicalLocation SARIFPhysicalLocation `json:"physicalLocation"`
}

// SARIFPhysicalLocation represents a physical location.
type SARIFPhysicalLocation struct {
	ArtifactLocation SARIFArtifactLocation `json:"artifactLocation"`
}

// SARIFArtifactLocation represents an artifact location.
type SARIFArtifactLocation struct {
	URI string `json:"uri"`
}

// ToSARIF converts the policy document to SARIF format.
func (d *Document) ToSARIF(version string) ([]byte, error) {
	if version == "" {
		version = "0.1.0"
	}

	report := SARIFReport{
		Schema:  "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
		Version: "2.1.0",
		Runs: []SARIFRun{
			{
				Tool: SARIFTool{
					Driver: SARIFDriver{
						Name:    "iampg",
						Version: version,
						Rules: []SARIFRule{
							{
								ID:               "iampg/permission-detected",
								Name:             "IAM Permission Detected",
								ShortDescription: SARIFMessage{Text: "AWS IAM permission detected"},
								FullDescription:  SARIFMessage{Text: "An AWS IAM permission was detected during analysis"},
								DefaultConfig:    SARIFRuleConfig{Level: "note"},
							},
							{
								ID:               "iampg/wildcard-resource",
								Name:             "Wildcard Resource",
								ShortDescription: SARIFMessage{Text: "Wildcard resource in IAM policy"},
								FullDescription:  SARIFMessage{Text: "A wildcard (*) resource was detected which may grant overly broad permissions"},
								DefaultConfig:    SARIFRuleConfig{Level: "warning"},
							},
							{
								ID:               "iampg/wildcard-action",
								Name:             "Wildcard Action",
								ShortDescription: SARIFMessage{Text: "Wildcard action in IAM policy"},
								FullDescription:  SARIFMessage{Text: "A wildcard (*) action was detected which may grant overly broad permissions"},
								DefaultConfig:    SARIFRuleConfig{Level: "warning"},
							},
						},
					},
				},
				Results: d.toSARIFResults(),
			},
		},
	}

	return json.MarshalIndent(report, "", "  ")
}

func (d *Document) toSARIFResults() []SARIFResult {
	var results []SARIFResult

	for _, stmt := range d.Statement {
		for _, action := range stmt.Action {
			// Check for wildcard actions
			if strings.Contains(action, "*") {
				results = append(results, SARIFResult{
					RuleID:  "iampg/wildcard-action",
					Level:   "warning",
					Message: SARIFMessage{Text: fmt.Sprintf("Wildcard action detected: %s", action)},
				})
			} else {
				results = append(results, SARIFResult{
					RuleID:  "iampg/permission-detected",
					Level:   "note",
					Message: SARIFMessage{Text: fmt.Sprintf("Permission: %s on %s", action, stmt.Resource)},
				})
			}
		}

		// Check for wildcard resources
		if stmt.Resource == "*" {
			results = append(results, SARIFResult{
				RuleID:  "iampg/wildcard-resource",
				Level:   "warning",
				Message: SARIFMessage{Text: "Wildcard resource (*) grants access to all resources"},
			})
		}
	}

	return results
}

// Format outputs the policy in the specified format.
func (d *Document) Format(format Format, options map[string]string) ([]byte, error) {
	switch format {
	case FormatJSON:
		return d.ToJSON()
	case FormatYAML:
		return d.ToYAML()
	case FormatTerraform:
		return d.ToTerraform(options["resource_name"])
	case FormatSARIF:
		return d.ToSARIF(options["version"])
	default:
		return nil, fmt.Errorf("unknown format: %s", format)
	}
}
